clc; clear; close all;
clear functions
load('compare.mat');
global logs
logs = struct('t', [], 'e1', [], 's', [], 'xi_hat', []);
for k = 1:3
    logs = struct('t', [], 'tau', [], 'e1', [], 'e2', [], 's', [], 'xi_hat', []);
      param = struct('m1', 1, 'm2', 1.5, 'l1', 2, 'l2', 2, 'r1', 0.5, 'r2', 0.8, 'J1', 5, 'J2', 5, 'g', 9.8, ...
        'sigma1', 1, 'sigma2', 0.8, 'sigma3', 1, 'sigma4',1, 'sigma5', 1, 'alpha1', 0.5, 'alpha2', 1.5, 'beta', 0.6, 'mu1', 1, 'mu2', 1, 'mu11', 0.9, 'mu22', 1.1,  'gamma1', 0.8, 'gamma2', 1.2,  'eta1', 0.4, 'eta2', 0.5, 'eta3',0.3);  
     x0 = [0.5; 2; 0; 0; 0; 0; 0;];  
    tspan  = [0,5]; 
    [t, x] = ode45(@(t,x)euler_lagrange_dynamics(t,x,param),tspan, x0);
    theta_d = [1.5 - 1.3*exp(-t) + 0.5*exp(-4*t), 1.3 + exp(-t) - 0.5*exp(-4*t)];
    dtheta_d = [1.3*exp(-t) - 2*exp(-4*t), -exp(-t) + 2*exp(-4*t)];
    theta_actual = x(:,1:2);  
    xi_hat = x(:,5:7);  
    e = theta_actual - theta_d; 
    e11 = e(:,1);  
color_blue   = [0  , 112, 192]/255;    
color_purple = [112, 48 , 160]/255;
color_green  = [112, 173,  71]/255;
end
figure;
subplot(2,1,1); 
plot(t, x(:,1), 'Color', color_blue,  'linewidth',1.5);
hold on;
plot(t, theta_d(:,1), 'LineStyle', '--', 'Color', color_green,'linewidth',1.5);
plot(tc, xc(:,1), 'Color', color_purple,'linewidth',1.5);
xlabel('Time (seconds)'); ylabel('q_1'); 
legend('Proposed','Desired','Method in [37]');
box off;grid on;ax = gca;  ax.XGrid = 'off';  ax.YGrid = 'on'; 
subplot(2,1,2); 
plot(t, x(:,2), 'Color', color_blue,  'linewidth',1.5);
hold on;
plot(t, theta_d(:,2),'LineStyle', '--', 'Color', color_green,'linewidth',1.5);
plot(tc, xc(:,2), 'Color', color_purple,'linewidth',1.5);
xlabel('Time (seconds)'); ylabel('q_2'); 
legend('Proposed','Desired','Method in [37]');
box off;grid on;ax = gca;  ax.XGrid = 'off';  ax.YGrid = 'on'; 
figure;
subplot(2,1,1); 
plot(t, x(:,3), 'Color', color_blue, 'linewidth',1.5);
hold on;
plot(t, dtheta_d(:,1),'LineStyle', '--', 'Color', color_green,'linewidth',1.5);
plot(tc, xc(:,3), 'Color', color_purple,'linewidth',1.5);
xlabel('Time (seconds)'); ylabel('v_1'); 
legend('Proposed','Desired','Method in [37]');
box off;grid on;ax = gca;  ax.XGrid = 'off';  ax.YGrid = 'on'; 
subplot(2,1,2); 
plot(t, x(:,4), 'Color', color_blue, 'linewidth',1.5);
hold on;
plot(t, dtheta_d(:,2),'LineStyle', '--', 'Color', color_green,'linewidth',1.5);
plot(tc, xc(:,4), 'Color', color_purple,'linewidth',1.5);
xlabel('Time (seconds)'); ylabel('v_2'); 
legend('Proposed','Desired','Method in [37]');
box off;grid on;ax = gca;  ax.XGrid = 'off';  ax.YGrid = 'on'; 
figure;
subplot(2,1,1);
plot(t, e(:,1),'Color', color_blue,'linewidth',1.5); 
hold on;
plot(tc, ec(:,1), 'Color', color_purple,'linewidth',1.5);
xlabel('Time (seconds)'); ylabel('e_1'); 
legend('Proposed', 'Method in [37]');
box off;grid on;ax = gca;  ax.XGrid = 'off';  ax.YGrid = 'on'; 
subplot(2,1,2);
plot(t, e(:,2),'Color', color_blue,'linewidth',1.5); 
hold on;
plot(tc, ec(:,2), 'Color', color_purple,'linewidth',1.5);
xlabel('Time (seconds)'); ylabel('e_2');
legend('Proposed', 'Method in [37]');
box off;grid on;ax = gca;  ax.XGrid = 'off';  ax.YGrid = 'on'; 
figure;
plot(logs.t, logs.s','linewidth',1.5); 
xlabel('Time (seconds)'); ylabel('s'); 
legend('s_1','s_2'); 
box off;grid on;ax = gca;  ax.XGrid = 'off';  ax.YGrid = 'on'; 
figure;
plot(logs.t, logs.xi_hat','linewidth',1.5); 
xlabel('Time (seconds)'); ylabel('Estimation of \zeta_i'); 
legend('\zeta_1','\zeta_2','\zeta_3'); 
box off;grid on;ax = gca;  ax.XGrid = 'off';  ax.YGrid = 'on'; 